-- Islands Dark — точная цветовая схема из GoLand
vim.g.colors_name = "islands"

local hl = vim.api.nvim_set_hl

-- === ОСНОВНЫЕ ===
hl(0, "Normal", { fg = "#bcbec4", bg = "#191a1c" })
hl(0, "NormalNC", { fg = "#bcbec4", bg = "#191a1c" })
hl(0, "NormalFloat", { bg = "#27282b" })
hl(0, "FloatBorder", { fg = "#393b40", bg = "#27282b" })
hl(0, "FloatTitle", { fg = "#ced0d6", bg = "#27282b" })

-- === ОБЩИЙ СИНТАКСИС ===
hl(0, "Keyword", { fg = "#cf8e6d" })
hl(0, "Statement", { fg = "#cf8e6d" })
hl(0, "Conditional", { fg = "#cf8e6d" })
hl(0, "Repeat", { fg = "#cf8e6d" })
hl(0, "Label", { fg = "#cf8e6d" })
hl(0, "Exception", { fg = "#cf8e6d" })
hl(0, "Function", { fg = "#56a8f5" })
hl(0, "Identifier", { fg = "#bcbec4" })
hl(0, "Type", { fg = "#56a8f5" })
hl(0, "Structure", { fg = "#56a8f5" })
hl(0, "Typedef", { fg = "#56a8f5" })
hl(0, "Constant", { fg = "#c77dbb" })
hl(0, "Boolean", { fg = "#c77dbb" })
hl(0, "Character", { fg = "#c77dbb" })
hl(0, "Number", { fg = "#2aacb8" })
hl(0, "Float", { fg = "#2aacb8" })
hl(0, "String", { fg = "#6aab73" })
hl(0, "Operator", { fg = "#bcbec4" })
hl(0, "Comment", { fg = "#7a7e85" })
hl(0, "SpecialComment", { fg = "#7a7e85" })
hl(0, "Special", { fg = "#bcbec4" })
hl(0, "Delimiter", { fg = "#bcbec4" })
hl(0, "Tag", { fg = "#bcbec4" })
hl(0, "Include", { fg = "#cf8e6d" })
hl(0, "PreProc", { fg = "#cf8e6d" })
hl(0, "Define", { fg = "#cf8e6d" })
hl(0, "Macro", { fg = "#cf8e6d" })
hl(0, "TypeParameter", { fg = "#16baac" })

-- === GO VIM SYNTAX ===
hl(0, "goStatement", { fg = "#cf8e6d" })
hl(0, "goConditional", { fg = "#cf8e6d" })
hl(0, "goLabel", { fg = "#cf8e6d" })
hl(0, "goRepeat", { fg = "#cf8e6d" })
hl(0, "goDeclType", { fg = "#cf8e6d" })
hl(0, "goDeclaration", { fg = "#cf8e6d" })
hl(0, "goBuiltins", { fg = "#56a8f5" })
hl(0, "goBoolean", { fg = "#c77dbb" })
hl(0, "goPredefinedIdentifiers", { fg = "#c77dbb" })
hl(0, "goFunctionCall", { fg = "#56a8f5" })
hl(0, "goMethodCall", { fg = "#56a8f5" })
hl(0, "goFunction", { fg = "#56a8f5" })
hl(0, "goType", { fg = "#56a8f5" })
hl(0, "goUnsignedInts", { fg = "#2aacb8" })
hl(0, "goFloats", { fg = "#2aacb8" })
hl(0, "goImaginary", { fg = "#2aacb8" })
hl(0, "goVarDefs", { fg = "#bcbec4" })
hl(0, "goVarAssign", { fg = "#bcbec4" })
hl(0, "goVar", { fg = "#cf8e6d" })
hl(0, "goConst", { fg = "#cf8e6d" })
hl(0, "goTypeDecl", { fg = "#cf8e6d" })
hl(0, "goFuncDecl", { fg = "#cf8e6d" })
hl(0, "goStructDecl", { fg = "#cf8e6d" })
hl(0, "goStructDef", { fg = "#bcbec4" })
hl(0, "goField", { fg = "#c77dbb" })
hl(0, "goReceiverVar", { fg = "#56a8f5" })
hl(0, "goParamName", { fg = "#56a8f5" })
hl(0, "goEnumDecl", { fg = "#cf8e6d" })
hl(0, "goEnumDef", { fg = "#bcbec4" })
hl(0, "goTypeDef", { fg = "#56a8f5" })
hl(0, "goTypeDefDecl", { fg = "#cf8e6d" })
hl(0, "goTypeConstructor", { fg = "#56a8f5" })
hl(0, "goEscape", { fg = "#cf8e6d" })
hl(0, "goEscapeError", { fg = "#f75464" })
hl(0, "goDoublequoteString", { fg = "#6aab73" })
hl(0, "goRawString", { fg = "#6aab73" })
hl(0, "goFormatSpecifier", { fg = "#6aab73" })
hl(0, "goString", { fg = "#6aab73" })
hl(0, "goCharacter", { fg = "#6aab73" })
hl(0, "goCharacterFmt", { fg = "#cf8e6d" })
hl(0, "goCharacterError", { fg = "#f75464" })
hl(0, "goOctalError", { fg = "#f75464" })
hl(0, "goHexError", { fg = "#f75464" })
hl(0, "goOctalNumber", { fg = "#2aacb8" })
hl(0, "goHexNumber", { fg = "#2aacb8" })
hl(0, "goDecimalNumber", { fg = "#2aacb8" })
hl(0, "goFloatNumber", { fg = "#2aacb8" })
hl(0, "goImaginaryNumber", { fg = "#2aacb8" })
hl(0, "goComplexNumber", { fg = "#2aacb8" })
hl(0, "goDirective", { fg = "#cf8e6d" })
hl(0, "goExternalType", { fg = "#56a8f5" })
hl(0, "goSpaceError", { fg = "#f75464" })
hl(0, "goDeclarationObj", { fg = "#bcbec4" })
hl(0, "goPredeclaredConst", { fg = "#c77dbb" })
hl(0, "goPredeclaredType", { fg = "#bcbec4" })

-- === TREE-SITTER (наши кастомные capture groups) ===
hl(0, "@keyword.all", { fg = "#cf8e6d" })
hl(0, "@keyword", { fg = "#cf8e6d" })
hl(0, "@keyword.function", { fg = "#cf8e6d" })
hl(0, "@keyword.return", { fg = "#cf8e6d" })
hl(0, "@keyword.import", { fg = "#cf8e6d" })
hl(0, "@keyword.type", { fg = "#cf8e6d" })
hl(0, "@keyword.conditional", { fg = "#cf8e6d" })
hl(0, "@keyword.channel", { fg = "#cf8e6d" })
hl(0, "@keyword.coroutine", { fg = "#cf8e6d" })
hl(0, "@keyword.repeat", { fg = "#cf8e6d" })
hl(0, "@conditional", { fg = "#cf8e6d" })
hl(0, "@repeat", { fg = "#cf8e6d" })
hl(0, "@exception", { fg = "#cf8e6d" })
hl(0, "@label", { fg = "#cf8e6d" })

hl(0, "@function", { fg = "#56a8f5" })
hl(0, "@function.call", { fg = "#56a8f5" })
hl(0, "@function.builtin", { fg = "#56a8f5" })
hl(0, "@function.method", { fg = "#57aaf7" })
hl(0, "@function.method.call", { fg = "#57aaf7" })
hl(0, "@method", { fg = "#57aaf7" })
hl(0, "@method.call", { fg = "#57aaf7" })
hl(0, "@constructor", { fg = "#56a8f5" })

-- Типы — голубой (contestUseCase, UserContext)
hl(0, "@type", { fg = "#56a8f5" })
hl(0, "@type.builtin", { fg = "#bcbec4" })
hl(0, "@type.definition", { fg = "#56a8f5" })
hl(0, "@type.qualifier", { fg = "#cf8e6d" })
hl(0, "@structure", { fg = "#56a8f5" })

hl(0, "@constant", { fg = "#c77dbb" })
hl(0, "@constant.builtin", { fg = "#c77dbb" })
hl(0, "@constant.macro", { fg = "#c77dbb" })
hl(0, "@boolean", { fg = "#c77dbb" })
hl(0, "@builtin", { fg = "#c77dbb" })
hl(0, "@number", { fg = "#2aacb8" })
hl(0, "@number.float", { fg = "#2aacb8" })
hl(0, "@number.hex", { fg = "#2aacb8" })
hl(0, "@number.oct", { fg = "#2aacb8" })

hl(0, "@string", { fg = "#6aab73" })
hl(0, "@string.escape", { fg = "#cf8e6d" })
hl(0, "@string.special", { fg = "#cf8e6d" })
hl(0, "@string.special.symbol", { fg = "#cf8e6d" })
hl(0, "@string.special.tag", { fg = "#6aab73" })
hl(0, "@string.format", { fg = "#cf8e6d" })
hl(0, "@string.special.url", { fg = "#5c92ff" })
hl(0, "@string.special.path", { fg = "#5c92ff" })

hl(0, "@variable", { fg = "#bcbec4" })
hl(0, "@variable.builtin", { fg = "#c77dbb" })
hl(0, "@variable.parameter", { fg = "#56a8f5" })
hl(0, "@parameter", { fg = "#56a8f5" })
hl(0, "@receiver", { fg = "#56a8f5" })
hl(0, "@variable.member", { fg = "#c77dbb" })
hl(0, "@field", { fg = "#c77dbb" })
hl(0, "@property", { fg = "#c77dbb" })

-- Пакеты и импорты — зеленоватый
hl(0, "@namespace", { fg = "#6aab73" })
hl(0, "@namespace.import", { fg = "#6aab73" })
hl(0, "@namespace.alias", { fg = "#6aab73" })
hl(0, "@module", { fg = "#6aab73" })

hl(0, "@operator", { fg = "#bcbec4" })
hl(0, "@punctuation.bracket", { fg = "#bcbec4" })
hl(0, "@punctuation.delimiter", { fg = "#bcbec4" })
hl(0, "@punctuation.special", { fg = "#bcbec4" })

hl(0, "@comment", { fg = "#7a7e85" })
hl(0, "@comment.documentation", { fg = "#5f826b" })
hl(0, "@comment.error", { fg = "#f75464" })
hl(0, "@comment.warning", { fg = "#f2c55c" })
hl(0, "@comment.note", { fg = "#8bb33d" })

hl(0, "@tag", { fg = "#d5b778" })
hl(0, "@tag.attribute", { fg = "#bcbec4" })
hl(0, "@tag.delimiter", { fg = "#d5b778" })

hl(0, "@attribute", { fg = "#b3ae60" })
hl(0, "@diff.plus", { fg = "#549159" })
hl(0, "@diff.minus", { fg = "#868a91" })
hl(0, "@diff.delta", { fg = "#375fad" })

-- === ИНТЕРФЕЙС ===
hl(0, "Cursor", { fg = "#191a1c", bg = "#ced0d6" })
hl(0, "CursorLine", { bg = "#1f2024" })
hl(0, "CursorLineNr", { fg = "#a1a3ab", bg = "#1f2024" })
hl(0, "CursorColumn", { bg = "#1f2024" })
hl(0, "LineNr", { fg = "#4b5059", bg = "#191a1c" })
hl(0, "LineNrAbove", { fg = "#4b5059" })
hl(0, "LineNrBelow", { fg = "#4b5059" })
hl(0, "Visual", { bg = "#2d543f" })
hl(0, "VisualNOS", { bg = "#2d543f" })
hl(0, "Search", { bg = "#2d543f", fg = "#bcbec4" })
hl(0, "IncSearch", { bg = "#114957", fg = "#bcbec4" })
hl(0, "CurSearch", { bg = "#114957", fg = "#bcbec4" })
hl(0, "MatchParen", { bg = "#43454a", bold = true })
hl(0, "StatusLine", { fg = "#bcbec4", bg = "#2b2d30" })
hl(0, "StatusLineNC", { fg = "#6f737a", bg = "#2b2d30" })
hl(0, "VertSplit", { fg = "#323438", bg = "#191a1c" })
hl(0, "WinSeparator", { fg = "#323438", bg = "#191a1c" })
hl(0, "SignColumn", { bg = "#191a1c" })
hl(0, "FoldColumn", { fg = "#4b5059", bg = "#191a1c" })
hl(0, "Folded", { fg = "#868991", bg = "#393b40" })
hl(0, "Pmenu", { fg = "#bcbec4", bg = "#27282b" })
hl(0, "PmenuSel", { fg = "#ced0d6", bg = "#393b40" })
hl(0, "PmenuSbar", { bg = "#27282b" })
hl(0, "PmenuThumb", { bg = "#43454a" })
hl(0, "DiagnosticHint", { fg = "#868a91" })
hl(0, "DiagnosticInfo", { fg = "#56a8f5" })
hl(0, "DiagnosticWarn", { fg = "#e0bb65" })
hl(0, "DiagnosticError", { fg = "#f75464" })
hl(0, "DiagnosticOk", { fg = "#6aab73" })
hl(0, "DiagnosticUnderlineHint", { sp = "#868a91", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#56a8f5", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#f2c55c", undercurl = true })
hl(0, "DiagnosticUnderlineError", { sp = "#fa6675", undercurl = true })
hl(0, "DiagnosticVirtualTextHint", { fg = "#868a91", bg = "#393b40" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#56a8f5", bg = "#393b40" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#e0bb65", bg = "#393b40" })
hl(0, "DiagnosticVirtualTextError", { fg = "#f75464", bg = "#393b40" })
hl(0, "DiagnosticVirtualTextOk", { fg = "#6aab73", bg = "#393b40" })
hl(0, "LspReferenceRead", { bg = "#373b39" })
hl(0, "LspReferenceText", { bg = "#373b39" })
hl(0, "LspReferenceWrite", { bg = "#402f33" })
hl(0, "LspInlayHint", { fg = "#868a91", bg = "#393b40" })
hl(0, "LspCodeLens", { fg = "#868a91", bg = "#393b40" })
hl(0, "LspSignatureActiveParameter", { fg = "#83acfc", bg = "#35538f" })
hl(0, "DiffAdd", { bg = "#293c40" })
hl(0, "DiffChange", { bg = "#293c40" })
hl(0, "DiffDelete", { bg = "#293c40" })
hl(0, "DiffText", { bg = "#2a5091" })
hl(0, "DiffAdded", { fg = "#549159" })
hl(0, "DiffModified", { fg = "#375fad" })
hl(0, "DiffRemoved", { fg = "#868a91" })
hl(0, "IndentBlanklineChar", { fg = "#323438" })
hl(0, "IndentGuid", { fg = "#323438" })
hl(0, "IndentBlanklineContextChar", { fg = "#4e5157" })
hl(0, "WinBar", { fg = "#9da0a8", bg = "#2b2d30" })
hl(0, "WinBarNC", { fg = "#6f737a", bg = "#2b2d30" })
hl(0, "Whitespace", { fg = "#6f737a" })
hl(0, "NonText", { fg = "#6f737a" })
hl(0, "SpecialKey", { fg = "#6f737a" })
hl(0, "TabLine", { fg = "#6f737a", bg = "#2b2d30" })
hl(0, "TabLineSel", { fg = "#dfe1e5", bg = "#2b2d30" })
hl(0, "TabLineFill", { bg = "#2b2d30" })
hl(0, "Title", { fg = "#ced0d6", bold = true })
hl(0, "Underlined", { fg = "#548af7", sp = "#548af7", underline = true })
hl(0, "Todo", { fg = "#8bb33d", bold = true })
hl(0, "SpecialChar", { fg = "#cf8e6d" })

-- === ДОПОЛНИТЕЛЬНЫЕ ЦВЕТА ИЗ Islands_Dark.icls ===
-- Гиперссылки
hl(0, "FollowedHyperlink", { fg = "#b189f5", sp = "#b189f5", underline = true })

-- Консоль
hl(0, "MsgArea", { fg = "#bcbec4" })
hl(0, "MsgError", { fg = "#f75464" })
hl(0, "MsgWarning", { fg = "#e0bb65" })
hl(0, "MsgSeparator", { bg = "#2b2d30" })

-- Логи
hl(0, "LogInfo", { fg = "#e0bb65" })
hl(0, "LogVerbose", { fg = "#56a8f5" })
hl(0, "LogDebug", { fg = "#bcbec4" })

-- Breadcrumbs
hl(0, "BreadcrumbsCurrent", { fg = "#dfe1e5", bg = "#2b2d30" })
hl(0, "BreadcrumbsDefault", { fg = "#9da0a8" })
hl(0, "BreadcrumbsInactive", { fg = "#6f737a" })

-- HTML/XML
hl(0, "htmlTagName", { fg = "#d5b778" })
hl(0, "htmlArg", { fg = "#bcbec4" })
hl(0, "htmlTag", { fg = "#d5b778" })
hl(0, "xmlTagName", { fg = "#d5b778" })
hl(0, "xmlTag", { fg = "#d5b778" })
hl(0, "xmlEntity", { fg = "#56a8f5" })
hl(0, "htmlCustomTag", { fg = "#2fbaa3" })

-- Markdown
hl(0, "markdownLinkText", { fg = "#56a8f5", sp = "#56a8f5", underline = true })
hl(0, "markdownUrl", { fg = "#56a8f5", sp = "#56a8f5", underline = true })

-- CSS
hl(0, "cssColor", { fg = "#56a8f5" })
hl(0, "cssUrl", { fg = "#5c92ff" })
hl(0, "cssImportant", { fg = "#cf8e6d", bold = true })

-- RegExp
hl(0, "regexpCharClass", { fg = "#b2ae60", bold = true })
hl(0, "regexpEscape", { fg = "#cf8e6d" })
hl(0, "regexpMeta", { fg = "#cf8e6d" })
hl(0, "regexpBraces", { fg = "#bcbec4" })
hl(0, "regexpBrackets", { fg = "#bcbec4" })
hl(0, "regexpParens", { fg = "#bcbec4" })
hl(0, "jsRegexp", { fg = "#42c3d4" })

-- Kotlin
hl(0, "kotlinLabel", { fg = "#32b8af" })
hl(0, "kotlinNamedArgument", { fg = "#56c1d6" })

-- Debug
hl(0, "DebugConsole", { fg = "#bcbec4" })
hl(0, "DebugConsoleError", { fg = "#f75464" })
hl(0, "DebugConsoleInfo", { fg = "#56a8f5" })
hl(0, "DebugConsoleWarn", { fg = "#e0bb65" })
hl(0, "DebugConsoleVerbose", { fg = "#56a8f5" })
hl(0, "DebugConsoleDebug", { fg = "#bcbec4" })
hl(0, "DebugConsoleInput", { fg = "#6aab73", italic = true })

-- Template variables
hl(0, "TemplateVariable", { fg = "#b189f5" })
